lesson: SpringBoot
spring:
  profiles:
    active: pro

enterprise:
  name: yang
  age: 20
  tel: 13866660000
  subject:
    - java
    - javascript
    - go

---
#开发
server:
  port: 80
spring:
  config:
    activate:
      on-profile: dev
---

#测试环境
server:
  port: 81
spring:
  config:
    activate:
      on-profile: test
---

#生产环境
server:
  port: 82
spring:
  config:
    activate:
      on-profile: pro
---
